os: osx
osx_image: xcode9.4
language: node_js
node_js:
  - "node"
  - "lts/*"
before_install:
  - brew update
  - brew install gs graphicsmagick
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm i -g codecov
  - npm i -g npm@latest
install:
  - npm install
script:
  - npm run test
after_success:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
git:
  depth: false
cache: npm
