matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.2
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gs graphicsmagick; fi
  - elsif [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get update                ; fi
  - elsif [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install graphicsmagick; fi
install:
  - npm install
  - npm run compile
language: node_js
node_js:
  - 4.1.2
  - 4.8.4
  - 5.12.0
  - 6.0.0
  - 6.8.1
  - 6.10.0
  - 7.10.0
  - 8.0.0
  - 8.5.0
  - 9.2.0